language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

before_script:
  - git clone github.com/git-ftp/git-ftp.git
  - cd git-ftp
  - sudo make install

script:
  - npm run build
  - npm install ftp
  - npm install chalk
  
after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle

branches:
  only:
    - master

# deploy:
#   skip_cleanup: true
#   provider: script
#   script: node deploy.js
#   on:
#     branch: master

env:
 global:
   - GH_REF: github.com/zhijunzhou/vue-gathering.git
